simple_facebook_pixel.settings:
  type: config_object
  label: 'Simple Facebook Pixel'
  mapping:
    pixel_enabled:
      type: boolean
      label: 'Enable Facebook Pixel'
    pixel_id:
      type: string
      label: 'Facebook Pixel ID'
    exclude_admin_pages:
      type: boolean
      label: 'Exclude admin pages'
    excluded_roles:
      type: sequence
      label: 'Exclude Facebook Pixel for the following roles'
      sequence:
        type: string
        label: 'Role'
    view_content_entities:
      type: sequence
      label: 'Add ViewContent event to the following pages'
      sequence:
        type: string
        label: 'Entity'
    complete_registration_enabled:
      type: boolean
      label: 'Enable'
    initiate_checkout_enabled:
      type: boolean
      label: 'Enable'
    purchase_enabled:
      type: boolean
      label: 'Enable'
    add_to_cart_enabled:
      type: boolean
      label: 'Enable'
    add_to_wishlist_enabled:
      type: boolean
      label: 'Enable'
